### ISSUE TITLE
Show functions not working

### ISSUE THREAD

**Issue by giuseppeangri** [jdalrymple/node-gitlab#100]
Hi,
I tried to use the show functions (both in Users and Projects), but it doesn't work.

I use the functions in this way:

```javascript
gitlab.Users.show(userId)
    .then(
        (gitlabResponse) => {
            console.log(gitlabResponse);
        },
        (gitlabError) => {
            console.log(gitlabError);
        }
    );
```

I receive this error:

```javascript
TypeError: response.body is not iterable
    at .../node_modules/gitlab/dist/es5/infrastructure/RequestHelper.js:92:31
    at Generator.next (<anonymous>)
    at step (.../node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (.../node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at <anonymous>
```

Thanks for this library,
Greetings!

**Comment by jdalrymple** [comment]
Not sure how I missed this obvious error when I was testing smh. Nice catch

**Comment by giuseppeangri** [comment]
I already fixed this issue and also the other two issues that I detected (#101, #102).
I send you all in a pull request.
Let me know if there are question! 😃

Greetings!

**Comment by jdalrymple** [comment]
Yup I saw! I asked a question in the pr

**Comment by jdalrymple** [comment]
Going to push this in the release today! Just need to fix up the limiting :)
