### ISSUE TITLE
Version >= 3.8 crashes with StatusCodeError 400

### ISSUE THREAD

**Issue by max-wittig** [jdalrymple/node-gitlab#167]
Just updated node-gitlab to 3.8 from 3.5.

If node-gitlab >= 3.8 is used my script just crashes. <=3.7 works just fine.   

```javascript
const Gitlab = require('gitlab').default;
const api = new Gitlab({
  url: config.host,
  token: config.token
});
const owners = await api.ProjectMembers.all(projectId);
```

This is the error message:

```
StatusCodeError: 400 - {"error":"user_id is invalid"}
    at new StatusCodeError (/home/projects/***/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/projects/***/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/projects/***/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/projects/***/node_modules/request/request.js:185:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/projects/***/node_modules/request/request.js:1161:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/projects/***/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The reason can be found in ResourceMembers.js. Reverting this commit fixes the issue:
https://github.com/jdalrymple/node-gitlab/commit/e081a1629f33e3af172101b94977f281879539c9#diff-379104d7d595f3793c2d7380496cc3c3

I'm not sure how to fix this, other than reverting...

**Comment by casz** [comment]
you don't have to revert you simply have to pass `excludeInherited`
```javascript
const owners = await api.ProjectMembers.all(projectId, { excludeInherited: true });
```

**Comment by max-wittig** [comment]
Oh okay. But what does this do? Shouldn't there be a default that doesn't require any parameters?

**Comment by casz** [comment]
Sadly the change resource members was not considered breaking even though it broke the resulting data.
The default in 3.7 was it COULD only give you project members without inheritance, however now in 3.8 which should have been breaking you can now exclude inherited and the default was considered to be false. So suddenly you get corrupted data if you relied on not getting the inherited permisisons.

However I agree that user_id is invalid seems like something in the API is not working as intended 🗡 when requesting members.

**Comment by casz** [comment]
Seems that this API: `GET /projects/:id/members/:user_id`
https://docs.gitlab.com/ee/api/members.html#get-a-member-of-a-group-or-project
conflicts with this: `GET /projects/:id/members/all`
https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members

**Comment by max-wittig** [comment]
@casz GitLab always does that. I've encountered that so many times now. :man_facepalming: 
That change would be great!

**Comment by jdalrymple** [comment]
I can revert the change, lol i keep trying to stay up to date with the docs :upside_down_face:

**Comment by jdalrymple** [comment]
Just reverted it! Should be up on npm in a min or so
