### ISSUE TITLE
Project Import doesn't work as expected / Usage unclear

### ISSUE THREAD

**Issue by LRH539** [jdalrymple/node-gitlab#429]
**Description**

I've tried to import a project which I have successfully exported using this library, but now trying to upload a project, I receive an error.

**Steps to reproduce**

Try to upload a project with the library, it will complain about the path not being specified. `api.ProjectImportExport.import(file, path)`

**Expected behaviour**

The file should be uploaded using: `api.ProjectImportExport.import(file, path)` and behave identical to the behavior documented here: https://docs.gitlab.com/ee/api/project_import_export.html#import-a-file

**Actual behaviour**

I receive the following error: ```{ HTTPError: Bad Request
    at fn (**REDACTED**/node_modules/ky/umd.js:266:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  response:
   Response {
     size: 0,
     timeout: 0,
     [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
     [Symbol(Response internals)]:
      { url: 'https://**REDACTED**/api/v4/projects/import',
        status: 400,
        statusText: 'Bad Request',
        headers: [Headers],
        counter: 0 } },
  description: 'path is missing' }```

**Possible fixes**

Maybe I am using this wrong, then please let me know how this function is supposed to be used, but I've briefly checked the code and it seems that the function doesn't respect the path parameter.

**Comment by LRH539** [comment]
But the path parameter is still ignored, this is the path of the project this should be imported to. I assume the path will be read from the file content, so it’s not possible to change it?

**Comment by LRH539** [comment]
Looks good from what I can tell, now the function reflects the docs and I should be able to use it.
